language: node_js
node_js: 
  - "11.0"
branches: 
    only: 
      - master
script: 
  - npm install
  - npm run build
deploy:
  provider: firebase
  token:
    secure: ""
env:
  global:
    secure: nb9OPbovKhBV2ZXc250JhpGITSKkE2IV/2roCEReHc4Al99mfgm2UmritXNYksUeFV7gFgl+w+AwFFpbTuQzWsJ7GsyafnIL61bFoRern7TKrLoqse7e9AN2QsW5CB051nDMziZjh4Du9OyeaIPb2QanDdoDD7H2QKhGBzk8vhB6s5sj8gXfO1T7gIfaDQd2qhFqbuyzC08Rnc7eNYI2P9Y3Ma8qgvmQ8cWRIsHnJ0tuNNKv0e7j9NoGRSN7cxHBHq0A3LlhQvgHoDJNoaBUH3Um1x1ogI54wJYz/IrmoPOsm6QhYlmguoVrTMM1sfh/8+iYFPyF8Yr9Jq8KKst5C1m58TxllIpDhmcH9fVnV+z+WnUHg5W1sEqxzkvQ/EJMSaFtJT//ENFSGb3yVp5a0atx/IDB5mLCk9auRM7jn+RnMTJZPGRrBZ/k5xjoWDEz31YbFbQ0JurgxR6Zb/SdQiF5nBpc20H41v5NqDUslZ8BUhDvb/zG5Bdt86zTrGgASihMzrYtdtI1wFjGzf8CpcL+i4gFahWmpXL/VlVF/8D0VSaqGksalEi+fKKnBZ4fr2AI8O/pyxhjk/0ZgJ2tq7/qZbhuxoK286WgnmQL1mMDWZcCnmmjLpw0rULIyINNN+NGtU5bz7+uxvza7pZDzQLYJ/Vg53XT7OwiuKmo6jI=
